/**
 * Jolpica nationality (a demonym such as "Monegasque") → ISO 3166 flag code.
 * The flag tile compares demonyms, and the code picks the flag image.
 *
 * Started from the original game table. "Argentinian" is kept as an alias
 * because Jolpica has used both spellings (Colapinto broke the game in 2025).
 */
const FLAGS: Readonly<Record<string, string>> = {
  Afghan: "af",
  Albanian: "al",
  American: "us",
  Andorran: "ad",
  Angolan: "ao",
  Anguillan: "ai",
  Antiguan: "ag",
  Argentine: "ar",
  Armenian: "am",
  Australian: "au",
  Austrian: "at",
  Azerbaijani: "az",
  Bahamian: "bs",
  Bangladeshi: "bd",
  Barbadian: "bb",
  Belgian: "be",
  Beninese: "bj",
  Bhutanese: "bt",
  Botswanan: "bw",
  Brazilian: "br",
  British: "gb",
  Bulgarian: "bg",
  Burkinabé: "bf",
  Burundian: "bi",
  Cambodian: "kh",
  Cameroonian: "cm",
  Canadian: "ca",
  "Cape Verdean": "cv",
  Chadian: "td",
  Chilean: "cl",
  Chinese: "cn",
  Colombian: "co",
  "Costa Rican": "cr",
  Croatian: "hr",
  Cuban: "cu",
  Cypriot: "cy",
  Czech: "cz",
  Danish: "dk",
  Dominican: "do",
  Dutch: "nl",
  Ecuadorian: "ec",
  Egyptian: "eg",
  Emirati: "ae",
  "Equatorial Guinean": "gq",
  Eritrean: "er",
  Estonian: "ee",
  Ethiopian: "et",
  Fijian: "fj",
  Filipino: "ph",
  Finnish: "fi",
  French: "fr",
  Gabonese: "ga",
  Gambian: "gm",
  Georgian: "ge",
  German: "de",
  Ghanaian: "gh",
  Gibraltarian: "gi",
  Greek: "gr",
  Grenadian: "gd",
  Guatemalan: "gt",
  Guinean: "gn",
  Guyanese: "gy",
  Haitian: "ht",
  Honduran: "hn",
  "Hong Konger": "hk",
  Hungarian: "hu",
  Icelandic: "is",
  Indian: "in",
  Indonesian: "id",
  Iranian: "ir",
  Iraqi: "iq",
  Israeli: "il",
  Italian: "it",
  Jamaican: "jm",
  Japanese: "jp",
  Jordanian: "jo",
  Kazakh: "kz",
  Kenyan: "ke",
  Kuwaiti: "kw",
  Kyrgyz: "kg",
  Laotian: "la",
  Latvian: "lv",
  Lebanese: "lb",
  Liberian: "lr",
  Libyan: "ly",
  Liechtensteiner: "li",
  Lithuanian: "lt",
  Luxembourgish: "lu",
  Macedonian: "mk",
  Malagasy: "mg",
  Malawian: "mw",
  Malaysian: "my",
  Malian: "ml",
  Maltese: "mt",
  Marshallese: "mh",
  Mauritanian: "mr",
  Mauritian: "mu",
  Mexican: "mx",
  Micronesian: "fm",
  Moldovan: "md",
  Monegasque: "mc",
  Mongolian: "mn",
  Montenegrin: "me",
  Moroccan: "ma",
  Mozambican: "mz",
  Namibian: "na",
  Nepalese: "np",
  "New Zealander": "nz",
  Nicaraguan: "ni",
  Nigerian: "ng",
  Nigerien: "ne",
  "North Korean": "kp",
  Norwegian: "no",
  Omani: "om",
  Pakistani: "pk",
  Palauan: "pw",
  Panamanian: "pa",
  "Papua New Guinean": "pg",
  Paraguayan: "py",
  Peruvian: "pe",
  Polish: "pl",
  Portuguese: "pt",
  Qatari: "qa",
  Romanian: "ro",
  Russian: "ru",
  Rwandan: "rw",
  "Saint Lucian": "lc",
  "Saint Vincentian": "vc",
  Salvadoran: "sv",
  Samoan: "ws",
  "San Marinese": "sm",
  Saudi: "sa",
  Senegalese: "sn",
  Serbian: "rs",
  Seychellois: "sc",
  "Sierra Leonean": "sl",
  Singaporean: "sg",
  Slovak: "sk",
  Slovenian: "si",
  "Solomon Islander": "sb",
  Somali: "so",
  "South African": "za",
  "South Korean": "kr",
  "South Sudanese": "ss",
  Spanish: "es",
  "Sri Lankan": "lk",
  Sudanese: "sd",
  Surinamese: "sr",
  Swedish: "se",
  Syrian: "sy",
  Taiwanese: "tw",
  Tajikistani: "tj",
  Tanzanian: "tz",
  Thai: "th",
  Togolese: "tg",
  Tongan: "to",
  Trinidadian: "tt",
  Tunisian: "tn",
  Turkish: "tr",
  Turkmen: "tm",
  Tuvaluan: "tv",
  Ugandan: "ug",
  Ukrainian: "ua",
  Uruguayan: "uy",
  Uzbekistani: "uz",
  Vanuatuan: "vu",
  Venezuelan: "ve",
  Vietnamese: "vn",
  Yemeni: "ye",
  Zambian: "zm",
  Zimbabwean: "zw",
  Argentinian: "ar",
};

/** Flag code shown when a nationality isn't in the table: flag-icons' "unknown" flag. */
export const UNKNOWN_FLAG = "xx";

/** The flag code for a Jolpica nationality, or UNKNOWN_FLAG if the table lacks it. */
export function flagFor(nationality: string): string {
  return FLAGS[nationality.trim()] ?? UNKNOWN_FLAG;
}
